# Generated by Django 4.2.5 on 2024-02-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("FabricaClass", "0002_rename_nome_turma_legenda_turma_ano_letivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turma",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Curso",
                to="FabricaClass.curso",
            ),
        ),
    ]
