# Generated by Django 4.2.5 on 2024-02-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("FabricaClass", "0004_formulario_respostas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Criterios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booleano", models.BooleanField()),
                ("texto", models.TextField()),
                ("numerico", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FabricaClass.criterios",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formulario",
            name="pergunta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="FabricaClass.pergunta",
            ),
            preserve_default=False,
        ),
    ]
