# Generated by Django 4.2.5 on 2023-10-29 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("FabricaClass", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
        migrations.AddField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome"
            ),
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simpe",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="SIMPE"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="professor_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="professor_user_permissions", to="auth.permission"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Matricula"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="aluno_groups", to="auth.group"
                    ),
                ),
                (
                    "id_turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turma",
                        to="FabricaClass.turma",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="aluno_user_permissions", to="auth.permission"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aluno",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
