# Generated by Django 4.2.5 on 2023-10-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("FabricaClass", "0002_rename_nome_turma_legenda_turma_ano_letivo_and_more"),
        ("usuario", "0002_remove_usuario_cpf_remove_usuario_data_nascimento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="usuario",
        ),
        migrations.AddField(
            model_name="usuario",
            name="matricula",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Matricula/SIAPE"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.IntegerField(
                choices=[(1, "Professor"), (2, "Aluno")], default=2
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="turma",
                to="FabricaClass.turma",
            ),
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
    ]
