# Generated by Django 4.2.5 on 2024-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0003_remove_professor_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="password_reset_token",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Password Reset Token"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="password_reset_token_created",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Password Reset Token Created"
            ),
        ),
    ]
