# Generated by Django 4.2.5 on 2024-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0004_usuario_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Password Reset Token",
            ),
        ),
    ]
